In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Extracting the Test Data

In [2]:
df = pd.DataFrame(pd.read_csv('distiller_20200330.csv', header=0))

In [3]:
df.head()

,id,abv,age,average_user_rating,brand_name,cost_level,description,expert_rating,flavor_profile,name,origin,reviewer,tasting_notes,type,user_comments
0,0,40.0,NaN,81.8,Diageo,4,XR or Extra Rare is a bottling that includes w...,84.0,NaN,Crown Royal XR,"Manitoba, Canada",Stephanie Moreno,"The aroma is heavy on the spice, both from the...",Canadian,203
1,1,40.0,NaN,76.4,Brecon,1,The Penderyn Distillery opened in 2000 as a wh...,NaN,NaN,Brecon Gin,Wales,NaN,NaN,Distilled Gin,11
2,2,58.4,NaN,93.8,Rock Town,3,Made from a mash bill of 88% rye grown in Arka...,NaN,NaN,Rock Town Arkansas Single Barrel Reserve Rye,"Arkansas, USA",NaN,NaN,Rye,4
3,3,46.0,NaN,80.0,anCnoc,4,This particular expression is part of anCnoc's...,NaN,NaN,anCnoc Barrow,"Highlands, Scotland",NaN,NaN,Peated Single Malt,6
4,4,35.0,NaN,71.6,Bacardí,1,This is a flavored rum of Barbados cherries an...,NaN,NaN,Bacardí Torched Cherry Rum,Puerto Rico,NaN,NaN,Flavored Rum,6

In [4]:
df = df[(df['tasting_notes'].isnull() == False) & (df['flavor_profile'].isnull() == True)]
print(len(df))

df = df[['id', 'name', 'expert_rating', 'type', 'tasting_notes']]
df.sample(5)

1289

,id,name,expert_rating,type,tasting_notes
2155,2155,Tirado Gold Corn Whiskey,72.0,Corn,Tastes exactly like buckwheat pancakes with a ...
6617,6617,Sazerac Rye 18 Year (Fall 2019),92.0,Rye,The nose is quite aromatic with toasted cereal...
1891,1891,Absolut Juice Apple Edition,73.0,Flavored Vodka,This vodka's aroma is bright and very similar ...
3196,3196,Nikka Pure Malt Black Whisky,82.0,Peated Blended Malt,"Of the ""colored"" pure malt series, this feels ..."
1252,1252,Hanson of Sonoma Habanero Vodka,87.0,Flavored Vodka,For a vodka infused with habanero there is sur...

In [5]:
type_list = []

for item in df['type']:
    type_list.append(item)

type_list = list(set(type_list))

print(type_list)

['Flavored Rum', 'Blended American Whiskey', 'Flavored Gin', 'Dairy/Egg Liqueurs', 'Mezcal Añejo', 'Other Agave', 'Bourbon', 'Aged Rum', 'Eau-de-Vie', 'Calvados', 'Tennessee', 'Other Sugarcane', 'Spiced Rum', 'Grappa/Marc', 'Single Pot Still', 'Other Whiskey', 'Blended Malt', 'Other Brandy', 'Spirit', 'Rhum Agricole Blanc', 'Coffee Liqueurs', 'Tequila Mixto Gold', 'Herbal/Spice Liqueurs', 'Peated Blended Malt', 'Cachaça', 'Spanish', 'Barrel-Aged Gin', 'Sotol Reposado', 'Barrel-Aged Vodka', 'Unflavored Vodka', 'White', 'Canadian', 'London Dry Gin', 'Genever', 'Rhum Agricole Vieux', 'Tequila Extra Añejo', 'Flavored Whiskey', 'Fruit Liqueurs', 'Modern Gin', 'Tequila Añejo', 'Wheat Whiskey', 'Other Liqueurs', 'American Brandy', 'Compound Gin', 'Sotol Añejo', 'Single Malt', 'Dark Rum', 'Peated Single Malt', 'Cognac', 'Distilled Gin', 'Tequila Mixto Blanco', 'Genever-Style', 'Armagnac', 'Single Grain', 'Floral Liqueurs', 'Silver Rum', 'Corn', 'Tequila Reposado', 'Mezcal Joven', 'Sloe Gin & Variants', 'Navy-Strength Gin', 'Amaro', 'American Single Malt', 'Mezcal Reposado', 'Gold Rum', 'Bitter Liqueurs', 'Flavored Vodka', 'Peated Blend', 'Navy Rum', 'Blended', 'Tequila Blanco', 'Rye']

In [6]:
category= []

category_list = ['Whiskey', 'Brandy', 'Rum', 'Gin', 'Vodka', 'Tequila', 'Liqueurs/Bitters']

whiskey_list = ['Blended Malt', 'Tennessee', 'Peated Single Malt', 'Single Grain', 'Blended', 'Flavored Whiskey', 'Corn', 
                'American Single Malt', 'Blended Grain', 'Blended American Whiskey', 'Rye', 'Bourbon', 'Other Whiskey',
                'Single Malt', 'Wheat Whiskey', 'White', 'Peated Blend', 'Peated Blended Malt', 'Spirit', 'Single Pot Still',
                'Canadian', ]

brandy_list = ['Eau-de-Vie', 'Other Brandy', 'Grappa/Marc',  'Cognac', 'Armagnac', 'Calvados', 'Blanche Armagnac', 'American Brandy',
              'Pisco', ]

rum_list = ['Rhum Agricole Éléve Sous Bois', 'Spiced Rum', 'Gold Rum', 'Aged Rum', 'Aguardiente', 'Flavored Rum', 'Navy Rum',
            'Rhum Agricole Blanc', 'Cachaça', 'Dark Rum', 'Silver Rum', 'Rhum Agricole Vieux', 'Other Sugarcane']

gin_list = ['Distilled Gin', 'Flavored Gin', 'Old Tom Gin', 'Plymouth Gin', 'London Dry Gin', 'Navy-Strength Gin', 
            'Gin de Mahón', 'Compound Gin', 'Genever', 'Modern Gin', 'Genever-Style', 'Barrel-Aged Gin']

vodka_list = ['Unflavored Vodka', 'Flavored Vodka', ]

tequila_list = ['Tequila Añejo', 'Tequila Blanco', 'Tequila Mixto Blanco', 'Tequila Joven', 'Tequila Extra Añejo', 'Mezcal Joven',
               'Raicilla Blanco', 'Tequila Mixto Gold', 'Mezcal Reposado', 'Other Agave', 'Sotol Blanco', 'Tequila Reposado',
               'Sotol Añejo', 'Mezcal Añejo', ]

liqueur_list = ['Bitter Liqueurs', 'Sloe Gin & Variants', 'Chocolate Liqueurs', 'Other Liqueurs', 'Herbal/Spice Liqueurs',
                'Coffee Liqueurs', 'Amaro', 'Triple Sec/Curaçao', 'Fruit Liqueurs', 'Nut Liqueurs', 'Floral Liqueurs', 
                'Dairy/Egg Liqueurs']

for item in df['type']:

    if item in whiskey_list:
        category.append(category_list[0])
    
    elif item in brandy_list:
        category.append(category_list[1])
        
    elif item in rum_list:
        category.append(category_list[2])
        
    elif item in gin_list:
        category.append(category_list[3])
        
    elif item in vodka_list:
        category.append(category_list[4])
        
    elif item in tequila_list:
        category.append(category_list[5])
        
    else:
        category.append(category_list[6])     

print(category[-10:-1])
len(category)

['Whiskey', 'Whiskey', 'Rum', 'Rum', 'Whiskey', 'Whiskey', 'Rum', 'Tequila', 'Whiskey']

1289

In [7]:
df['type'] = category
df = df.rename(columns={'type':'category'})

df.head()

,id,name,expert_rating,category,tasting_notes
0,0,Crown Royal XR,84.0,Whiskey,"The aroma is heavy on the spice, both from the..."
8,8,Spirit of Texas Straight Silver Rum,80.0,Rum,"The aroma provides notes of butterscotch, vani..."
9,9,Bushmills Red Bush,85.0,Whiskey,The aroma is quite sweet on the Demerara sugar...
15,15,Old Ripy Kentucky Straight Bourbon,87.0,Whiskey,"The aromas are a bit muted initially, but once..."
17,17,John Jacob Rye Whiskey,86.0,Whiskey,"There's some sweet, almost floral heat on the ..."

In [8]:
category_list = []

for item in df['category']:
    category_list.append(item)

category_list = list(set(category_list))

print(category_list)

['Whiskey', 'Tequila', 'Gin', 'Vodka', 'Brandy', 'Liqueurs/Bitters', 'Rum']

In [9]:
df.head(5)

,id,name,expert_rating,category,tasting_notes
0,0,Crown Royal XR,84.0,Whiskey,"The aroma is heavy on the spice, both from the..."
8,8,Spirit of Texas Straight Silver Rum,80.0,Rum,"The aroma provides notes of butterscotch, vani..."
9,9,Bushmills Red Bush,85.0,Whiskey,The aroma is quite sweet on the Demerara sugar...
15,15,Old Ripy Kentucky Straight Bourbon,87.0,Whiskey,"The aromas are a bit muted initially, but once..."
17,17,John Jacob Rye Whiskey,86.0,Whiskey,"There's some sweet, almost floral heat on the ..."

In [10]:
from collections import Counter

for item in category_list:
    print(item+': ', Counter(df['category'] == item)[True])

Whiskey:  665
Tequila:  169
Gin:  36
Vodka:  87
Brandy:  43
Liqueurs/Bitters:  30
Rum:  259

In [11]:
tasting_notes_len = []

for item in df['tasting_notes']:
    tasting_notes_len.append(len(item))
    
print(sum(tasting_notes_len))
    
pd.Series(tasting_notes_len).describe()

477533

count    1289.000000
mean      370.467804
std       104.275230
min       120.000000
25%       303.000000
50%       357.000000
75%       425.000000
max       934.000000
dtype: float64

## Exporting as CSV

In [12]:
df2 = df[['id','name','category','tasting_notes']]
df2.head()

,id,name,category,tasting_notes
0,0,Crown Royal XR,Whiskey,"The aroma is heavy on the spice, both from the..."
8,8,Spirit of Texas Straight Silver Rum,Rum,"The aroma provides notes of butterscotch, vani..."
9,9,Bushmills Red Bush,Whiskey,The aroma is quite sweet on the Demerara sugar...
15,15,Old Ripy Kentucky Straight Bourbon,Whiskey,"The aromas are a bit muted initially, but once..."
17,17,John Jacob Rye Whiskey,Whiskey,"There's some sweet, almost floral heat on the ..."

In [13]:
df2.to_csv('test_data.csv', index=False)